CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(15) UNIQUE NOT NULL,
    pass_hash VARCHAR NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMPTZ NOT NULL
);
CREATE TABLE workouts (
    id BIGSERIAL PRIMARY KEY,
    author_id BIGSERIAL REFERENCES users(id) NOT NULL,
    date TIMESTAMPTZ NOT NULL,
    is_done BOOLEAN NOT NULL,
    type VARCHAR,
    duration INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE goals (
    id BIGSERIAL PRIMARY KEY,
    author_id BIGSERIAL REFERENCES users(id) NOT NULL,
    text TEXT NOT NULL,
    is_done BOOLEAN NOT NULL,
    deadline TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE user_roles(
    id BIGSERIAL PRIMARY KEY,
    author_id BIGSERIAL REFERENCES users(id) NOT NULL,
    role VARCHAR(10) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
)